[mypy]
strict = true
ignore_missing_imports = true
explicit_package_bases = true
plugins = pydantic.mypy
mypy_path = ./src

exclude = (?x)(
    ^build    # Skip build directories
    | ^(.*[/\\])?test_.*$  # Skip test files
  )
