name: Courts Process

on:
  repository_dispatch:
    types: [scrape-complete]
  workflow_dispatch:

jobs:
  courts-process:
    name: Process courts scraper results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::985454606291:role/gha-ujs-scraper
          aws-region: us-east-1
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - uses: taiki-e/install-action@just
      - name: Process results
        run: just etl-courts-process
        env:
          ENV: prod
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
      - name: Restart Fly API
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: just fly-restart
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
