name: Courts Process

on:
  repository_dispatch:
    types: [courts-scrape-complete]
  workflow_dispatch:

jobs:
  courts-process:
    name: Process courts scraper results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v4
      - uses: taiki-e/install-action@just
      - name: Process results
        run: just etl-courts-process
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
          ECS_SUBNET_IDS: ${{ vars.ECS_SUBNET_IDS }}
          ECS_SECURITY_GROUP_IDS: ${{ vars.ECS_SECURITY_GROUP_IDS }}
      - name: Restart Fly API
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: just fly-restart
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
