name: Courts Process

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Scraper run ID whose lease should be completed, if applicable."
        type: string
        required: true

permissions:
  contents: read
  id-token: write

concurrency:
  group: courts-production
  cancel-in-progress: false

jobs:
  courts-process:
    name: Process courts scraper results
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::985454606291:role/gha-ujs-scraper
          aws-region: us-east-1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          version: "0.12.0"
      - uses: taiki-e/install-action@5b4d68e2e660441203ab128a23676f1e4faf1532 # v2.86.3
        with:
          tool: just
      - name: Process results
        run: just etl-courts-process
        env:
          ENV: prod
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          RUN_ID: ${{ inputs.run_id }}
