name: Daily Shootings ETL

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  daily-sync-shootings:
    name: Daily Shootings Data Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::985454606291:role/gha-ujs-scraper
          aws-region: us-east-1
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - uses: taiki-e/install-action@just
      - name: Verify identity
        run: aws sts get-caller-identity
      - name: Run shootings ETL
        run: just etl-shootings
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_SCRAPER_PREFIX: ${{ vars.S3_SCRAPER_PREFIX }}
          S3_PROCESSED_PREFIX: ${{ vars.S3_PROCESSED_PREFIX }}
          S3_REFERENCE_PREFIX: ${{ vars.S3_REFERENCE_PREFIX }}
      - name: Restart Fly API
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: just fly-restart
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
